routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/', function () {
             return Redirect::to(route('home'));    
    });

    Route::resources([
       'tipos' => 'Configurar\TiposController',
       'cargos' => 'Configurar\CargosController',
       'ubicaciones' => 'Configurar\UbicacionController',
       'personal' => 'Carnets\PersonalController',
       'carnet' => 'Carnets\CarnetController',
       'usuarios' => 'Configurar\UsuariosController',  
      ]);
       
    
    Route::get('buscar','AjaxController@buscar')->name('buscar');
    Route::get('buscar_trabajador', 'AjaxController@buscar_trabajador')->name('buscar_trabajador');
     Route::get('buscar_ciudadano', 'AjaxController@buscar_ciudadano')->name('buscar_ciudadano');
    Route::post('estatus/actualizar','Configurar\EstatusController@actualizar')->name('estatus.actualizar');


    Route::post('estatus/eliminar','Configurar\EstatusController@eliminar')->name('estatus.eliminar');

    Route::post('procedencia/actualizar','Configurar\ProcedenciaController@actualizar')->name('procedencia.actualizar');

    Route::post('procedencia/eliminar','Configurar\ProcedenciaController@eliminar')->name('procedencia.eliminar');

    Route::get('imprimir/{id}','Carnets\CarnetController@imprimir')->name('carnet.imprimir');

    Route::post('tipo/actualizar','Configurar\TipoController@actualizar')->name('tipo.actualizar');

    Route::post('tipo/eliminar','Configurar\TipoController@eliminar')->name('tipo.eliminar');
    Route::get('buscarModelo','AjaxController@buscarModelo')->name('buscarModelo');
    Route::post('solicitud/buscar','Registro\SolicitudController@buscar')->name('solicitud.buscar');    
        
    Route::post('solicitud/buscarcategoria','Registro\SolicitudController@buscar_categorias')->name('solicitud.buscarcategoria');    
        
    Route::get('solicitud/destroy/{id}', [
            'uses' => 'Registro\SolicitudController@destroy',
            'as'   => 'solicitud.destroy'
           ]);

   

    Route::post('categorias/actualizar','Configurar\CategoriasController@actualizar')->name('categorias.actualizar');

    Route::post('categorias/eliminar','Configurar\CategoriasController@eliminar')->name('categorias.eliminar');  

    Route::post('usuarios/estatus','Configurar\UsuariosController@status')->name('usuarios.estatus');
           Route::get('/usuarios/cambiar/{id}', [
            'uses' => 'Configurar\UsuariosController@cambiar',
            'as'   => 'usuarios.cambiar'
           ]);

    Route::put('/usuarios/update_password/{valor}', [
                'uses' => 'Configurar\UsuariosController@update_password',
                'as'   => 'usuarios.update_password'
            ]);

    Route::post('crear/usuario','UsuariosController@store')->name('crear.usuario');
           
   

    
});    

app/Tipos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tipos extends Model
{
    protected $table = 'tipo';
}

app/Http/Controllers/Configurar/CargosController.php
<?php

namespace App\Http\Controllers\Configurar;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Cargos;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\File;
use Carbon\Carbon;
use Illuminate\Support\Str;
use Auth;

class CargosController extends Controller
{
     public function __construct()
    {
      $this->middleware('auth');
    }

    public function index()
    {
       $cargos = Cargos::orderby('id','asc')->get();
       return view('Configurar.Cargos.index',compact('cargos'));
    }

    public function create()
    {
      return view('Configurar.cargos.create');
    }

    public function edit($id)
    {
        $cargo = Cargos::where('id',$id)->first();
        return view('Configurar.Cargos.edit',compact('cargo'));
    }
    public function show($id)
    {
        
    }

    public function store(Request $request)
    {
      $descripcion = $request["descripcion"];
      if($descripcion!=""){
        $cargos = Cargos::where('descripcion',$descripcion)->first();
        if($cargos!=null){
           \Session::flash('mensajeError', 'Cargo Ya Registrado');
        }else{


             $cargo = new Cargos;
             $cargo->descripcion = $descripcion; 

             $cargo->id_usuario = auth()->id();  
             $cargo->save();  
             \Session::flash('mensaje', 'Cargo creado con éxito');
        }
      }
      return redirect()->route("cargos.index");
    }

    public function update(Request $request,$id)
    {
        $cargo = cargos::where('id',$id)->first();
        if($cargo!=null){
                        
        
             $cargo->descripcion = $request->descripcion; 
             if($name!="")$cargo->url_imagen = $name;
             #$cargo->id_estatus = 1;
             $cargo->save();  
             \Session::flash('mensaje', 'cargo actualizado con éxito'); 
             }
              return redirect()->route("cargos.index");   
    }

}

app/Http/Controllers/Configurar/TiposController.php
<?php

namespace App\Http\Controllers\Configurar;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Tipos;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\File;
use Carbon\Carbon;
use Illuminate\Support\Str;
use Auth;

class TiposController extends Controller
{
     public function __construct()
    {
      $this->middleware('auth');
    }

    public function index()
    {
       $tipos = Tipos::orderby('id','asc')->get();
       return view('Configurar.Tipos.index',compact('tipos'));
    }

    public function create()
    {
      return view('Configurar.Tipos.create');
    }

    public function edit($id)
    {
        $tipo = Tipos::where('id',$id)->first();
        return view('Configurar.Tipos.edit',compact('tipo'));
    }
    public function show($id)
    {
        
    }

    public function store(Request $request)
    {
      $descripcion = $request["descripcion"];
      if($descripcion!=""){
        $tipos = Tipos::where('descripcion',$descripcion)->first();
        if($tipos!=null){
           \Session::flash('mensajeError', 'Tipo Ya Registrado');
        }else{

        if($request->hasFile('url_imagen')){
                   $nombre ="tipo ";
                   $archivo_nombre =Str::slug($nombre, '-');
                   $archivo_nombre = $archivo_nombre.'-'.Carbon::now()->format('YmdHis');       
                     $name = $archivo_nombre.'.'.$request->url_imagen->getClientOriginalExtension();
                 $name_file = Storage::disk('public')->putFileAs('img/tipo', new File($request->url_imagen), $name,'public');
              
                 }else{$name="";} 

             $tipo = new Tipos;
             $tipo->descripcion = $descripcion; 
             $tipo->url_imagen = $name;
             $tipo->id_estatus = 1;
             $tipo->id_usuario = auth()->id();  
             $tipo->save();  
             \Session::flash('mensaje', 'Tipo creado con éxito');
        }
      }
      return redirect()->route("tipos.index");
    }

    public function update(Request $request,$id)
    {
        $tipo = Tipos::where('id',$id)->first();
        if($tipo!=null){
          if($request->hasFile('url_imagen')){
                       $nombre ="tipo ";
                       $archivo_nombre =Str::slug($nombre, '-');
                       $archivo_nombre = $archivo_nombre.'-'.Carbon::now()->format('YmdHis');       
                         $name = $archivo_nombre.'.'.$request->url_imagen->getClientOriginalExtension();
                     $name_file = Storage::disk('public')->putFileAs('img/tipo', new File($request->url_imagen), $name,'public');
                  
                     }else{$name="";} 
                            
        
             $tipo->descripcion = $request->descripcion; 
             if($name!="")$tipo->url_imagen = $name;
             #$tipo->id_estatus = 1;
             $tipo->save();  
             \Session::flash('mensaje', 'Tipo actualizado con éxito'); 
             }
              return redirect()->route("tipos.index");   
    }

}

app/Http/Controllers/Configurar/UbicacionController.php
<?php

namespace App\Http\Controllers\Configurar;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Ubicacion as Ubicaciones;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\File;
use Carbon\Carbon;
use Illuminate\Support\Str;
use Auth;

class UbicacionController extends Controller
{
     public function __construct()
    {
      $this->middleware('auth');
    }

    public function index()
    {
       $ubicaciones = Ubicaciones::orderby('id','asc')->get();
       return view('Configurar.Ubicaciones.index',compact('ubicaciones'));
    }

    public function create()
    {
      return view('Configurar.Ubicaciones.create');
    }

    public function edit($id)
    {
        $cargo = Ubicaciones::where('id',$id)->first();
        return view('Configurar.Ubicaciones.edit',compact('cargo'));
    }
    public function show($id)
    {
        
    }

    public function store(Request $request)
    {
      $descripcion = $request["descripcion"];
      if($descripcion!=""){
        $ubicaciones = Ubicaciones::where('descripcion',$descripcion)->first();
        if($ubicaciones!=null){
           \Session::flash('mensajeError', 'Ubicación Ya Registrado');
        }else{


             $cargo = new Ubicaciones;
             $cargo->descripcion = $descripcion; 

             $cargo->id_usuario = auth()->id();  
             $cargo->save();  
             \Session::flash('mensaje', 'Ubicación creado con éxito');
        }
      }
      return redirect()->route("ubicaciones.index");
    }

    public function update(Request $request,$id)
    {
        $cargo = Ubicaciones::where('id',$id)->first();
        if($cargo!=null){
                        
        
             $cargo->descripcion = $request->descripcion; 
             $cargo->save();  
             \Session::flash('mensaje', 'Ubicación actualizado con éxito'); 
             }
              return redirect()->route("ubicaciones.index");   
    }

}

app/Http/Controllers/Configurar/UsuariosController.php
<?php

namespace App\Http\Controllers\Configurar;

use Illuminate\Http\Request;
use App\roleuser;
use App\Http\Controllers\Controller;
use App\User;
use App\Role;
use Illuminate\Support\Facades\Hash;
use Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Foundation\Auth\RegistersUsers;
@session_start();


class UsuariosController extends Controller
{

     use RegistersUsers;

	  public function __construct()
    {
      $this->middleware('auth');
    }
    
 protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'role_id' => ['required', 'string', 'integer'],
        ]);
    }


public function show($user_id)
{
 
}
  
 public function edit($user_id)
    {
        $user = User::select(DB::raw('users.id, email, users.name, users.created_at, roles.descripcion, role_user.role_id'))
                    ->join('role_user', 'users.id', '=', 'role_user.user_id')
                    ->join('roles', 'role_user.role_id', '=', 'roles.id')
                    ->where('users.id',$user_id)
                    ->first();
        $roles = Role::get();        
        // dd($user->role_id);

        return view('Configurar.Usuarios.edit',['user'=>$user,'roles'=>$roles]);
    }





public function update(Request $request,$user_id)
    {

        $user = User::where('id', $user_id)->first();

        if (!$user){
            return view('Configurar.Usuarios.index');
        }
        else{
            $user = User::find($user_id)
            ->fill($request->input());
            $user->save();
            $user = DB::table('role_user')
                    ->where('user_id', $user_id)
                    ->update(['role_id'=>$request["role_id"]]);
            return redirect()->route("usuarios.index");
        }
    }

public function create(){
     $roles = Role::get();
 
        return view('Configurar.Usuarios.register',['roles'=>$roles]);
}

 public function status(Request $request)

    {
        $user_id = $request["id"];
        $user = User::find($user_id);
        if ($user->id_estado == null) {
              $user = User::where('id', $user_id)
                        ->update(['id_estado'=>1]); 
                        $anterior=0;
                        $actual=1;  
          }  
          elseif ($user->id_estado == 1) {
              $user = User::where('id', $user_id)
                        ->update(['id_estado'=>2]); 
                                 $anterior=1;
                        $actual=2; 
          }
          else{
            $user = User::where('id', $user_id)
                        ->update(['id_estado'=>1]); 
                $anterior=2;
               $actual=1;                  
          }
     if($anterior==1 && $actual==2)
     {
        /*$eliminarol = roleuser::where('user_id',$user_id)->first();
        $id = $eliminarol->id;
        $eliminarol->destroy($id);*/
     }
      if($anterior==2 && $actual==1)
     {
        $agregarol = roleuser::where('user_id',$user_id)->first();
        if($agregarol==NULL){
        $agregarol = new roleuser();
        $agregarol->user_id = $user_id;
        $agregarol->rol_id = $user->rol_id;
        $agregarol->save();
       }
     }    
     if($anterior==0 && $actual==1)
     {
         $agregarol = roleuser::where('user_id',$user_id)->first();
        if($agregarol==NULL){
        $agregarol = new roleuser();
        $agregarol->user_id = $user_id;
        $agregarol->rol_id = $user->rol_id;
        $agregarol->save();
      }
     }    
        return $user;
    }

  public function index()
    {
        $usuarios = User::select(DB::raw('users.id, email, users.name, users.created_at, roles.descripcion, users.id_estado'))
                    ->join('role_user', 'users.id', '=', 'role_user.user_id')
                    ->join('roles', 'role_user.role_id', '=', 'roles.id')
                    ->orderBy('users.created_at','desc')
                    ->get();       

        // dd($usuarios);
        return view('Configurar.Usuarios.index',['usuarios'=>$usuarios]);        
    }


   public function store(Request $request)
   {
   			$rules = [
			'email' => 'required|email|unique:users,email',
			'password' => 'required|string|min:6|confirmed',
			
		];
		try {
			$validator = \Validator::make($request->all(), $rules);
			if ($validator->fails()){
				return back()->withErrors($validator)->withInput();
			}
			//dd($request);
			$role_admin = Role::where('id', $request["role_id"])->first();
			$usuario               = new User($request->all());
			$usuario->name         = $request["name"];
			$usuario->email        = $request["email"];
			$usuario->password     = Hash::make($request->password);
            $usuario->id_estado    = 1;
            $usuario->rol_id    = $request->role_id;
            $usuario->save();
            $usuario->roles()->attach($role_admin);
            
			return redirect()->route('usuarios.index')->with("notificacion","Se ha guardado correctamente su información");
		} catch (Exception $e) {
			\Log::info('Error creating item: '.$e);
			return \Response::json(['created' => false], 500);
		}

   }

  public function cambiar($id)
  {
        //dd($id);
    $usuario=User::find($id);
    return view('Configurar.Usuarios.cambiarp')->with('usuario',$usuario);
  }

  public function update_password(Request $request, $valor)
  {
      //dd($valor);
      $id=$valor;
      $password = Hash::make($request->password);
      $usuarios=User::find($id);
      $usuarios->password = $password;
      $usuarios->save();
      return redirect()->route('usuarios.index')->with("notificacion","Se ha guardado correctamente su información");            
  }


}

resources/views/Configurar/Tipos/create.blade.php
@extends('layouts.layout')
@section('titulo', 'Configurar')
@section('titulo2', 'Tipo Personal')
 @section('link_back',route("tipos.index"))
@section('link_new_none','d-none')
@section('content')

            <div class="container-xxl flex-grow-1 container-p-y">
                <form action="{{ route('tipos.store')}}" method="POST" enctype="multipart/form-data" >
                  {{ csrf_field() }}
              <div class="row">
              <div class="col-md-6">
                  <div class="card mb-4">
                    <h5 class="card-header">Crear</h5>
                    <div class="card-body">
                      <div>
                        <label for="defaultFormControlInput" class="form-label">Descripción y/o Nombre</label>
                        <input type="text" class="form-control" id="descripcion" name="descripcion" placeholder="Descripcion" aria-describedby="defaultFormControlHelp">
                        <div id="defaultFormControlHelp" class="form-text">
                          Ingrese Tipo de Carnet
                        </div>
                      </div>
                    </div>
                  </div>
                </div>  
<div class="col-md-6">
                  <div class="card mb-4">
                    <h5 class="card-header">Plantilla de Diseño</h5>
                    <div class="card-body">
                      <div class="form-floating">
                        <input type="file" class="form-control" id="url_imagen" name="url_imagen">
                        <label for="floatingInput">Seleccione Imagen</label>
                        <div id="floatingInputHelp" class="form-text">
                          <img class="card-img-top" src="{{ asset('sneat/assets/img/elements/5.jpg') }}" id="imgSalida" alt="Card image cap">
                          We'll never share your details with anyone else.
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
<div class="col-md-6">
  <div class="card mb-2">
                  <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
</div>
                </div>
                </form>
                <!--/ Transactions -->
              </div>

@endsection
@push('scripts')

<script  type="text/javascript" charset="utf-8" >
   
  $('#url_imagen').change(function(e) {
      addImage(e); 
    });

   

    function addImage(e){
      var file = e.target.files[0],
      imageType = /image.*/;
      if (!file.type.match(imageType))
        return;

      var reader = new FileReader();
      reader.onload = fileOnload;
      reader.readAsDataURL(file);
    }

    function fileOnload(e) {
      var result=e.target.result;
      $('#imgSalida').attr("src",result);
    }

   

  
   
   
  



  
</script>



@endpush

resources/views/Configurar/Tipos/edit.blade.php
@extends('layouts.layout')
@section('titulo', 'Configurar')
@section('titulo2', 'Tipo Personal')
 @section('link_back',route("tipos.index"))
@section('link_new_none','d-none')
@section('content')

            <div class="container-xxl flex-grow-1 container-p-y">
                <form action="{{ route('tipos.update',$tipo->id)}}" method="POST" enctype="multipart/form-data" >
                  {{ csrf_field() }}
@method('PUT') 
<input type="hidden" name="id" value="{{ $tipo->id }}">
              <div class="row">
              <div class="col-md-6">
                  <div class="card mb-4">
                    <h5 class="card-header">Editar</h5>
                    <div class="card-body">
                      <div>
                        <label for="defaultFormControlInput" class="form-label">Descripción y/o Nombre</label>
                        <input type="text" class="form-control" id="descripcion" name="descripcion" placeholder="Descripcion" aria-describedby="defaultFormControlHelp" value="{{ $tipo->descripcion }}">
                        <div id="defaultFormControlHelp" class="form-text">
                          Ingrese Tipo de Carnet
                        </div>
                      </div>
                    </div>
                  </div>
                </div>  
<div class="col-md-6">
  <?php

 $archivo = 'img/tipo/'.$tipo->url_imagen;
 if (Storage::disk('public')->exists($archivo) == true)
    {
      $archivo = Storage::disk('public')->url($archivo);
    }
  else{
    $archivo="sneat/assets/img/elements/5.jpg";
   }
   
?>
  <div class="card mb-4">
      <h5 class="card-header">Plantilla de Diseño</h5>
      <div class="card-body">
          <div class="form-floating">
                        <input type="file" class="form-control" id="url_imagen" name="url_imagen">
                        <label for="floatingInput">Seleccione Imagen</label>
                        <div id="floatingInputHelp" class="form-text">
                          <img class="card-img-top" src="{{ asset($archivo) }}" id="imgSalida" alt="Card image cap">
                          
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
<div class="col-md-6">
  <div class="card mb-2">
                  <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
</div>
                </div>
                </form>
                <!--/ Transactions -->
              </div>

@endsection
@push('scripts')

<script  type="text/javascript" charset="utf-8" >
   
  $('#url_imagen').change(function(e) {
      addImage(e); 
    });

   

    function addImage(e){
      var file = e.target.files[0],
      imageType = /image.*/;
      if (!file.type.match(imageType))
        return;

      var reader = new FileReader();
      reader.onload = fileOnload;
      reader.readAsDataURL(file);
    }

    function fileOnload(e) {
      var result=e.target.result;
      $('#imgSalida').attr("src",result);
    }

   

  
   
   
  



  
</script>



@endpush

resources/views/Configurar/Tipos/index.blade.php
@extends('layouts.layout')
@section('titulo', 'Configurar')
@section('titulo2', 'Tipo Personal')
 @section('link_back',route("home"))
 @section('link_new',route('tipos.create'))
@section('content')
  <div class="container-xxl flex-grow-1 container-p-y">
@if(Session::has('mensaje'))

<div class="bs-toast toast fade show bg-primary" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                          <i class="bx bx-bell me-2"></i>
              <div class="me-auto fw-semibold">Siscarn</div>
                <small>Exito</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
              <div class="toast-body">
                          {!!Session::get('mensaje')!!}
                  </div>
            </div>

@endif
@if(Session::has('mensajeError'))
<div class="bs-toast toast fade show bg-danger" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                          <i class="bx bx-bell me-2"></i>
              <div class="me-auto fw-semibold">Siscarn</div>
                <small>Exito</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
              <div class="toast-body">
                          {!!Session::get('mensajeError')!!}
                  </div>
            </div>
@endif
<div class="row">
<div class="card">
                <h5 class="card-header">Lista</h5>
                <div class="table-responsive text-nowrap">
                  <table class="table data-table">
                    <thead class="table-light">
                      <tr>
                        <th>#</th>
                        <th>Descripción</th>
                        <th>Status</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                    <tbody class="table-border-bottom-0">
                      @foreach($tipos as $key)
                      <tr>
                        <td>{{ $key->id }}</td>
                        <td>{{ $key->descripcion }}</td>
                       
                        <td><span class="badge bg-label-primary me-1">Active</span></td>
                        <td>
                          <div class="dropdown">
                            <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                              <i class="bx bx-dots-vertical-rounded"></i>
                            </button>
                            <div class="dropdown-menu">
                              <a class="dropdown-item" href="{{ route('tipos.edit',$key->id) }}"><i class="bx bx-edit-alt me-1"></i> Editar</a>
                              <a class="dropdown-item" href="{{ route('tipos.destroy',$key->id) }}"><i class="bx bx-trash me-1"></i> Delete</a>
                            </div>
                          </div>
                        </td>
                      </tr>
                    @endforeach
                    </tbody>
                  </table>
                </div>
              </div>                </div>
                <!--/ Transactions -->
              </div>

@endsection
@push("scripts")
<script type="text/javascript">
  $(function () {

    

    var table = $('.data-table').DataTable({

      "language": {
      "url": "https://cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
    },      

    });

    

  });  


</script>
@endpush